import kotlinx.kover.gradle.plugin.dsl.CoverageUnit

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kover)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "jp.trackrail.shopclipper"
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = "jp.trackrail.shopclipper"
        minSdk = 24
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // 🔴 The key itself is NOT in this repository (規約 §9): it lives in
    // 99_secret/keystores/ShopClipper-upload.jks and its passwords in
    // %USERPROFILE%/.gradle/gradle.properties as SHOPCLIPPER_UPLOAD_*.
    // Every value is orNull, so a PC without those properties still builds
    // debug - only the release build needs them (規約 §12 V2).
    // ⚠ ShopClipper is not on Google Play, so there is no Play App Signing:
    // this key IS the app signing key and cannot be reset (計画書 D16).
    signingConfigs {
        create("upload") {
            storeFile = providers.gradleProperty("SHOPCLIPPER_UPLOAD_STORE_FILE").orNull?.let { file(it) }
            storePassword = providers.gradleProperty("SHOPCLIPPER_UPLOAD_STORE_PASSWORD").orNull
            keyAlias = providers.gradleProperty("SHOPCLIPPER_UPLOAD_KEY_ALIAS").orNull
            keyPassword = providers.gradleProperty("SHOPCLIPPER_UPLOAD_KEY_PASSWORD").orNull
        }
    }

    buildTypes {
        release {
            // AGP 9 carries this block in place of isMinifyEnabled; the
            // template generated it as false. Turning it on means the build
            // that runs on the device is R8-optimized, so a class R8 removed
            // shows up here rather than after release (計画書 R8・規約 §10.2).
            optimization {
                enable = true
            }
            signingConfig = signingConfigs.getByName("upload")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
    }
}

kover {
    reports {
        filters {
            excludes {
                // Activity / Fragment / BuildConfig / DataBinding (Kover's Android preset)
                androidGeneratedClasses()
                // UI (@Composable and @Preview) is out of scope for C1
                annotatedBy("androidx.compose.runtime.Composable")
                // Classes generated by the Compose compiler
                classes("*ComposableSingletons*")
                // Theme definitions (colors, typography, shapes)
                packages("*.ui.theme")
                // kotlinx.serialization generates write$Self inside every @Serializable
                // model (140 branches for the 4 Todoist models, measured 2026-09-20).
                // The models only hold fields; their JSON is tested in ModelsTest.
                annotatedBy("kotlinx.serialization.Serializable")
                // Need the device itself (the Keystore and the network); checked
                // by hand on the device instead (計画書 §8・I4/I5).
                // The "*" also takes the lambda classes the compiler generates
                // inside them (UrlConnectionTransport$execute$2 and friends).
                classes(
                    "jp.trackrail.shopclipper.data.KeystoreTokenCipher*",
                    "jp.trackrail.shopclipper.net.UrlConnectionTransport*",
                )
            }
        }
        verify {
            rule {
                // Fail when branch (C1) coverage is below the bound
                minBound(90, CoverageUnit.BRANCH)
            }
        }
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)
}